#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xAB4655A126D292E4 (coreteam@netfilter.org)
#
Name     : libnetfilter_acct
Version  : 1.0.3
Release  : 3
URL      : https://www.netfilter.org/projects/libnetfilter_acct/files/libnetfilter_acct-1.0.3.tar.bz2
Source0  : https://www.netfilter.org/projects/libnetfilter_acct/files/libnetfilter_acct-1.0.3.tar.bz2
Source1  : https://www.netfilter.org/projects/libnetfilter_acct/files/libnetfilter_acct-1.0.3.tar.bz2.sig
Summary  : Netfilter extended accounting infrastructure library
Group    : Development/Tools
License  : LGPL-2.1
Requires: libnetfilter_acct-lib = %{version}-%{release}
Requires: libnetfilter_acct-license = %{version}-%{release}
BuildRequires : pkgconfig(libmnl)

%description
= nfacct: the extended accounting infrastructure for Netfilter =
Netfilter provides three accounting mechanisms:

%package dev
Summary: dev components for the libnetfilter_acct package.
Group: Development
Requires: libnetfilter_acct-lib = %{version}-%{release}
Provides: libnetfilter_acct-devel = %{version}-%{release}
Requires: libnetfilter_acct = %{version}-%{release}

%description dev
dev components for the libnetfilter_acct package.


%package lib
Summary: lib components for the libnetfilter_acct package.
Group: Libraries
Requires: libnetfilter_acct-license = %{version}-%{release}

%description lib
lib components for the libnetfilter_acct package.


%package license
Summary: license components for the libnetfilter_acct package.
Group: Default

%description license
license components for the libnetfilter_acct package.


%prep
%setup -q -n libnetfilter_acct-1.0.3
cd %{_builddir}/libnetfilter_acct-1.0.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604353062
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1604353062
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libnetfilter_acct
cp %{_builddir}/libnetfilter_acct-1.0.3/COPYING %{buildroot}/usr/share/package-licenses/libnetfilter_acct/01a6b4bf79aca9b556822601186afab86e8c4fbf
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/libnetfilter_acct/libnetfilter_acct.h
/usr/lib64/libnetfilter_acct.so
/usr/lib64/pkgconfig/libnetfilter_acct.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libnetfilter_acct.so.1
/usr/lib64/libnetfilter_acct.so.1.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libnetfilter_acct/01a6b4bf79aca9b556822601186afab86e8c4fbf
